development:
  adapter: postgresql
  encoding: unicode
  database: Portfolio_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Portfolio_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Portfolio_production
  pool: 5
  username: postgres
  password:
